# fly.toml app configuration file generated for cruise-terraforming-mars on 2024-08-06T19:00:55+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cruise-terraforming-mars'
primary_region = 'arn'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  MAX_GAME_DAYS = "60"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
